variables:
  LATEST_VER: angristan/hastebin:latest

stages:
  - Build image
  - Push to Docker Hub

docker-build:
  image: docker:stable
  stage: Build image
  script:
  - docker info
  - docker build -t $LATEST_VER .

docker push:
  image: docker:stable
  stage: Push to Docker Hub
  only:
  - master
  script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push $LATEST_VER && docker image rm $LATEST_VER
